#!/usr/bin/env python3
"""Remove generated bytecode and temporary eval artifacts from the active OZM package."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

os.environ.setdefault("PYTHONDONTWRITEBYTECODE", "1")
sys.dont_write_bytecode = True


def remove_bytecode(root: Path) -> list[str]:
    removed: list[str] = []
    for path in sorted(root.rglob("*.pyc")):
        removed.append(path.relative_to(root).as_posix())
        path.unlink(missing_ok=True)
    for path in sorted(root.rglob("__pycache__"), reverse=True):
        if path.is_dir():
            removed.append(path.relative_to(root).as_posix())
            shutil.rmtree(path)
    return removed


def bytecode_artifacts(root: Path) -> list[str]:
    artifacts = [path.relative_to(root).as_posix() for path in sorted(root.rglob("*.pyc"))]
    artifacts.extend(path.relative_to(root).as_posix() for path in sorted(root.rglob("__pycache__")) if path.is_dir())
    return sorted(set(artifacts))


def remove_temp_eval(root: Path) -> list[str]:
    removed: list[str] = []
    manager = root / "ozone-manager"
    for rel_path in [
        "references/eval-last-run.json",
        "references/tmp-eval-last-run.json",
    ]:
        path = manager / rel_path
        if path.exists():
            removed.append(path.relative_to(root).as_posix())
            path.unlink()
    return removed


LOCAL_PATH_RE = re.compile(r"(?i)(?:[A-Z]:[\\/](?:Users|Documents)[\\/][^\s`'\"<>)\]}]+|/(?:Users|home)/[^\s`'\"<>)\]}]+)")


def public_redaction(source_root: Path, public_root: Path) -> dict[str, object]:
    if public_root.exists():
        shutil.rmtree(public_root)
    shutil.copytree(source_root, public_root)
    removed: list[str] = []
    redacted: list[str] = []
    archive = public_root / "ozone-manager" / "references" / "archive"
    if archive.exists():
        removed.append(archive.relative_to(public_root).as_posix())
        shutil.rmtree(archive)
    for candidate in [
        public_root / "ozone-manager" / "references" / "hardening-log.md",
        public_root / "ozone-manager" / "references" / "package-manifest.json",
    ]:
        if not candidate.exists() or not candidate.is_file():
            continue
        text = candidate.read_text(encoding="utf-8", errors="ignore")
        new_text = LOCAL_PATH_RE.sub("<operator-local-path>", text)
        if new_text != text:
            candidate.write_text(new_text, encoding="utf-8")
            redacted.append(candidate.relative_to(public_root).as_posix())
    report = {
        "schema": "ozm.public_redaction_report.v1",
        "source": "<skills-root>",
        "publicRoot": "<public-root>",
        "removed": removed,
        "redacted": redacted,
        "policy": "archive removed; operator-local paths redacted for public distribution",
    }
    report_path = public_root / "ozone-manager" / "references" / "public-redaction-report.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Clean generated OZM package artifacts.")
    parser.add_argument("--skill-root", default=str(Path(__file__).resolve().parents[2]))
    parser.add_argument("--remove-bytecode", action="store_true")
    parser.add_argument("--remove-temp-eval", action="store_true")
    parser.add_argument("--check-only", action="store_true", help="Only inspect generated artifacts; do not remove anything.")
    parser.add_argument("--forbid-bytecode", action="store_true", help="Fail when __pycache__ or *.pyc exists under --skill-root.")
    parser.add_argument("--public", action="store_true", help="Create a public-redacted copy without mutating the source package.")
    parser.add_argument("--public-root", help="Destination for --public redacted copy; defaults beside skill root.")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    root = Path(args.skill_root).resolve()
    removed: list[str] = []
    before_bytecode = bytecode_artifacts(root)
    if args.remove_bytecode and not args.check_only:
        removed.extend(remove_bytecode(root))
    if args.remove_temp_eval:
        removed.extend(remove_temp_eval(root))
    public_report = None
    if args.public:
        public_root = Path(args.public_root).resolve() if args.public_root else root.parent / f"{root.name}-public"
        public_report = public_redaction(root, public_root)
    after_bytecode = bytecode_artifacts(root)
    issues = []
    if args.forbid_bytecode and after_bytecode:
        issues.append({
            "severity": "error",
            "code": "bytecode_artifact_present",
            "message": f"Bytecode artifacts remain under skill root: {after_bytecode[:5]}",
            "path": after_bytecode[0],
        })
    result = {
        "status": "fail" if issues else "pass",
        "removed": sorted(set(removed)),
        "removedCount": len(set(removed)),
        "bytecodeBefore": before_bytecode,
        "bytecodeAfter": after_bytecode,
        "issues": issues,
    }
    if public_report:
        result["publicRedactionReport"] = public_report
    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print(f"ozm_clean_package=pass removed={result['removedCount']}")
    return 0 if result["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
